name: Project Issue
description: Track a work item derived from requirements
title: "[REQ-###] <concise summary>"
labels: ["status: inbox"]
assignees: []

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
      description: "Set based on PROJECT_REQUIREMENTS.md"
    validations:
      required: true

  - type: input
    id: requirement
    attributes:
      label: Requirement ID
      placeholder: "REQ-###"
      description: "ID from PROJECT_REQUIREMENTS.md"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "What needs to be built/fixed (scope, constraints, context)?"
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - Condition 1
        - Condition 2
        - Condition 3
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes (optional)
      placeholder: "Affected modules, risks, perf concerns, migration notes"

  - type: textarea
    id: test_plan
    attributes:
      label: Test Plan
      placeholder: |
        - Unit:
        - Integration:
        - E2E:
        - Edge cases:
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:
        - label: Branch created from `dev` (name like `dev/<issue#>-short-summary`)
        - label: PR opened targeting `dev` and linked (e.g., “Closes #<issue>”)
        - label: Tests added/updated and CI green
        - label: Docs/notes updated if needed
        - label: Evidence attached/linked (logs, screenshots, report links)

  - type: textarea
    id: evidence
    attributes:
      label: Evidence / Reports
      placeholder: "CI run IDs, screenshots, logs, benchmark links, etc."

